name: AkaneCapture Release

on: [create]

jobs:
  build-default:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.3.0
        with:
          dotnet-version: 3.0.100

      - name: Build with dotnet
        run: dotnet publish ./Source/AkaneCapture/AkaneCapture.csproj --configuration Release

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: AkaneCapture-x64-default
      #     path: ./Source/AkaneCapture/bin/x64/Release/netcoreapp3.0/win10-x64/publish

  build-single-executable:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.3.0
        with:
          dotnet-version: 3.0.100

      - name: Patch [Single Executable]
        run: Get-Content ./patches/SingleExe.patch | patch -p1

      - name: Build with dotnet
        run: dotnet publish ./Source/AkaneCapture/AkaneCapture.csproj --configuration Release

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: AkaneCapture-x64-single-executable
      #     path: ./Source/AkaneCapture/bin/x64/Release/netcoreapp3.0/win10-x64/publish

  build-single-ready-to-run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.3.0
        with:
          dotnet-version: 3.0.100

      - name: Patch [Single Executable (Ready To Run)]
        run: Get-Content patches/SingleExeReadyToRun.patch | patch -p1

      - name: Build with dotnet
        run: dotnet publish ./Source/AkaneCapture/AkaneCapture.csproj --configuration Release
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: AkaneCapture-x64-single-executable-ready-to-run
      #     path: ./Source/AkaneCapture/bin/x64/Release/netcoreapp3.0/win10-x64/publish
